version: "3.0"
services:
  api:
    build: ./docker
    ports:
      - "8106:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/apache/sites-enabled:/etc/apache2/sites-enabled
      - ./docker/apache/logs:/var/log/apache2/
    links:
      - mysql:mysql

  mysql:
    image: mysql:5.7
    ports:
      - 3201:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=quick_daily_db
    logging:
      driver: none
    volumes:
      - ./docker/mysql/data:/var/lib/mysql