# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    Monolog\Formatter\JsonFormatter: ~
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Command handlers:
    app.command_handler.create_new_user_account:
        class: App\Application\Domain\Command\Handler\CreateNewUserAccountCommandHandler
        public: true

    # Presenters:
    app.presenter.create_new_user_api:
        class: App\Application\Infrastructure\UseCase\CreateNewUser\CreateNewUserApiPresenter
        public: true

    app.presenter.create_new_user_cli:
        class: App\Application\Infrastructure\UseCase\CreateNewUser\CreateNewUserPresenter
        public: true

    # Default presents implementations:
    App\Application\Domain\UseCase\CreateNewUser\CreateNewUserPresenterInterface: '@app.presenter.create_new_user_api'

    # Custom DI
    App\Command\CreateNewUserCommand:
        public: true
        bind:
            App\Application\Domain\UseCase\CreateNewUser\CreateNewUserPresenterInterface: '@app.presenter.create_new_user_cli'
